---
# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: infra
name: leapp
version: 1.0.0
readme: README.md
authors:
  - Bob Mader (github.com/swapdisk)
  - Mike Savage (github.com/heatmiser)
  - Jeffrey Cutter (github.com/jeffmcutter)
  - David Danielsson (github.com/djdanielsson)
description: Ansible collection for running the leapp tool
license_file: LICENSE
tags:
  # tags so people can search for collections https://galaxy.ansible.com/search
  # tags are all lower-case, no spaces, no dashes.
  - rhel
  - upgrades
  - linux
repository: https://github.com/oamg/ansible-leapp
# documentation: https://github.com/ansible-collection-migration/community.REPO_NAME/tree/main/docs
homepage: https://github.com/oamg/ansible-leapp
issues: https://github.com/oamg/ansible-leapp/issues
build_ignore:
  # https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
dependencies:
  "ansible.posix": ">=1.5.1"
  "fedora.linux_system_roles": '>=1.21.0'
  "community.general": '>=6.6.0'
...
