---
- name: leapp_newest_kernel_not_in_use | Boot to latest kernel
  block:

    - name: leapp_newest_kernel_not_in_use | Gather package facts
      ansible.builtin.package_facts:
        manager: rpm

    - name: leapp_newest_kernel_not_in_use | Sort kernels by RPM version (newest first)
      ansible.builtin.set_fact:
        sorted_kernels: "{{ ansible_facts.packages['kernel'] | infra.leapp.rpm_sort | reverse | list }}"

    - name: leapp_newest_kernel_not_in_use | Set fact for latest kernel version
      ansible.builtin.set_fact:
        latest_kernel_version: "{{ sorted_kernels[0].version }}-{{ sorted_kernels[0].release }}.{{ sorted_kernels[0].arch }}"

    - name: leapp_newest_kernel_not_in_use | Check current kernel version
      ansible.builtin.command: uname -r
      register: current_kernel
      changed_when: false

    - name: leapp_newest_kernel_not_in_use | Check the kernel versions
      ansible.builtin.debug:
        msg: "The newest kernel {{ latest_kernel_version }} is already in use. Skipping this task."
      when: latest_kernel_version == current_kernel.stdout

    - name: leapp_newest_kernel_not_in_use | Process remediation
      when: latest_kernel_version != current_kernel.stdout
      block:
        - name: leapp_newest_kernel_not_in_use | Set default kernel to latest
          ansible.builtin.command: grubby --set-default /boot/vmlinuz-{{ latest_kernel_version }}
          register: set_default_kernel
          changed_when: set_default_kernel is success

        - name: leapp_newest_kernel_not_in_use | Run zipl to update s390x boot record
          ansible.builtin.command: zipl
          when: ansible_facts['architecture'] == 's390x'
          changed_when: true

        - name: leapp_newest_kernel_not_in_use | Reboot into latest kernel
          ansible.builtin.reboot:
            reboot_timeout: "{{ leapp_reboot_timeout }}"
            post_reboot_delay: "{{ leapp_post_reboot_delay }}"
          timeout: "{{ leapp_reboot_timeout }}"

...
