---
- name: custom-local-repos | Enable custom upgrade yum repositories
  ansible.builtin.yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    enabled: "{{ item.enabled | default(1) }}"
    gpgcheck: "{{ item.gpgcheck | default(0) }}"
    gpgkey: "{{ item.gpgkey | default(omit) }}"
    repo_gpgcheck: "{{ item.repo_gpgcheck | default(omit) }}"
    file: "{{ item.file | default('local') }}"
    state: "{{ item.state | default('present') }}"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ __local_repos }}"

...
