---
- name: disable-previous-repo-files | Stat repo file
  ansible.builtin.stat:
    path: /etc/yum.repos.d/{{ item }}
  register: __repo_file_stat

- name: disable-previous-repo-files | Block to backup and remove repo file if found
  when: __repo_file_stat.stat.exists
  block:
    - name: disable-previous-repo-files | Backup repo files
      ansible.builtin.copy:
        remote_src: true
        src: /etc/yum.repos.d/{{ item }}
        dest: /etc/yum.repos.d/{{ item }}.{{ ansible_date_time.iso8601_basic_short }}
        owner: root
        group: root
        mode: "0644"

    - name: disable-previous-repo-files | Remove repo files
      ansible.builtin.file:
        path: /etc/yum.repos.d/{{ item }}
        state: absent

...
