---
- name: grub2-upgrade | Grub package is absent
  ansible.builtin.package:
    name: grub
    state: absent

- name: grub2-upgrade | Grub2 package is present
  ansible.builtin.package:
    name: grub2
    state: present

- name: grub2-upgrade | The /etc/default/grub file is templated
  ansible.builtin.template:
    src: etc_default_grub.j2
    dest: /etc/default/grub
    owner: root
    group: root
    mode: "0644"

# If grub_boot_device is not defined, attempt to determine it based on /boot if present, or / if /boot is not present.
- name: grub2-upgrade | Determine grub_boot_device if not defined
  when: grub_boot_device is not defined
  block:
    - name: grub2-upgrade | Determine if /boot is a mount point
      ansible.builtin.set_fact:
        boot_mounted: "{{ ansible_mounts | selectattr('mount', 'eq', '/boot') | list | length | bool }}"

    - name: grub2-upgrade | Get boot device dict from /boot
      ansible.builtin.set_fact:
        boot_device_dict: "{{ ansible_mounts | selectattr('mount', 'eq', '/boot') | list | first }}"
      when: boot_mounted

    - name: grub2-upgrade | Get boot device dict from /
      ansible.builtin.set_fact:
        boot_device_dict: "{{ ansible_mounts | selectattr('mount', 'eq', '/') | list | first }}"
      when: not boot_mounted

    - name: grub2-upgrade | Get boot device from boot device dict
      ansible.builtin.set_fact:
        grub_boot_device: "{{ boot_device_dict.device | regex_replace('[1-9]$', '') }}"

- name: grub2-upgrade | Run grub2-install
  ansible.builtin.shell: |
    export PATH={{ os_path }}
    grub2-install {{ grub_boot_device }}
  changed_when: true

- name: grub2-upgrade | Run grub2-mkconfig
  ansible.builtin.shell: |
    export PATH={{ os_path }}
    set -o pipefail
    grub2-mkconfig -o /boot/grub2/grub.cfg
    grub2-mkconfig -o /boot/efi/EFI/redhat/grub.cfg
  changed_when: true

- name: grub2-upgrade | Old grub.conf file is absent
  ansible.builtin.file:
    path: /boot/grub/grub.conf
    state: absent

- name: grub2-upgrade | Reboot to start using grub2
  ansible.builtin.reboot:
    reboot_timeout: "{{ reboot_timeout }}"
    post_reboot_delay: "{{ post_reboot_delay }}"
  timeout: "{{ reboot_timeout }}"

...
