---
- name: cleanup_logs | Ensure ansible_facts used by role
  ansible.builtin.include_tasks: set_facts.yml

- name: cleanup_logs | Cleanup | Remove log files
  ansible.builtin.shell: |
    set -euxo pipefail
    rm -f /var/log/leapp/*.log
    rm -f /var/log/leapp/*.json
    rm -f /var/log/leapp/*.txt
  changed_when: true
