---
- name: RHEL pre-upgrade analysis
  hosts: all
  become: true
  # strategy: free
  # gather_facts: true
  # force_handlers: true

  vars:
    # Upgrade type: cdn (default), satellite, rhui, or custom
    leapp_upgrade_type: satellite

    # Variables specific to satellite upgrade type
    leapp_satellite_organization: <satellite_org>
    leapp_satellite_activation_key: <activation_key>
    leapp_satellite_activation_key_post_analysis: <activation_key_post_analysis>

    # Additional variables that inflience the analysis execution (see roles/analysis/README.md)
    leapp_preupg_opts: --target 9.6
    leapp_answerfile: |
      [remove_pam_pkcs11_module_check]
      confirm = True
  tasks:
    - name: Generate pre-upgrade analysis report
      ansible.builtin.import_role:
        name: infra.leapp.analysis
...
