---
- name: Remediate
  hosts: all
  become: true
  # strategy: free
  # gather_facts: true
  # force_handlers: true

  vars:
    # Executes following remediations for all systems, use host_vars files
    # to specify remediations per managed node (see roles/remediate/README.md).
    leapp_remediation_todo:
      - leapp_firewalld_allowzonedrifting
      - leapp_missing_pkg
  tasks:
    - name: Perform remediations on the system
      ansible.builtin.import_role:
        name: infra.leapp.remediate
...
