---
name: Yaml and Ansible Lint
on: [workflow_call] # [push, pull_request, workflow_call]  # yamllint disable-line rule:truthy
permissions:
  contents: read
jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Build collection
        run: ansible-galaxy collection build -vvv
        shell: bash
        working-directory: ${{ github.workspace }}

      - name: Get version
        run: echo "NUM=$(cat galaxy.yml | grep version | cut -d ':' -f 2 | awk '{print $1}')" >> $GITHUB_OUTPUT
        id: vers

      - name: Install collection
        run: ansible-galaxy collection install ./infra-leapp-${{ steps.vers.outputs.NUM }}.tar.gz # -p /home/runner/collections
        shell: bash
        working-directory: ${{ github.workspace }}

      # - name: Install collection dependencies
      #   run: ansible-galaxy collection install -r requirements.yml

      - name: Run ansible-lint
        uses: ansible/ansible-lint@2bac76bbc98f420b20299cbbc4a52a8ce6cbc295 # main
        with:
          args: "--offline"
...
