---
name: Lint extra docsite docs and links
on:
  # Run CI against all pushes (direct commits, also merged PRs), Pull Requests
  push:
    branches:
      - main
      - stable-*
  pull_request:
  # Run CI once per day (at 06:00 UTC)
  # This ensures that even if there haven't been commits that we are still testing against latest version of ansible-test for each ansible-base version
  schedule:
    - cron: '0 6 * * *'

permissions:
  contents: read

jobs:
  docsite:
    name: Lint extra docsite docs and links
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: '3.12'

      - name: Install antsibull-docs
        run: pip install antsibull-docs --disable-pip-version-check

      - name: Run collection docs linter
        run: antsibull-docs lint-collection-docs .
...
